name: Release

on: workflow_dispatch

jobs:
  build:
    name: Create new builds
    runs-on: [self-hosted, ios-build]
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          clean: false
      - name: Pull Twine repo
        run: git -C $TWINE_FOLDER pull origin master
      - name: Setup tools
        run: ./scripts/setup.sh
      - name: Generate build number
        run: echo "BUILD_NUMBER=$(echo `date +"%y%m%d%H%M"`)" >> $GITHUB_ENV
      - name: Create builds
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        run: |
          fastlane build_alpha
          fastlane build_beta
          fastlane build_production
          fastlane tag

  deploy-alpha:
    name: Deploy alpha
    needs: build
    runs-on: [self-hosted, ios-alpha]
    timeout-minutes: 120
    steps:
      - name: Upload the Alpha build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        run: fastlane upload_testflight_alpha distribute_external:true

  deploy-beta:
    name: Deploy beta
    needs: build
    runs-on: [self-hosted, ios-beta]
    timeout-minutes: 120
    steps:
      - name: Upload the Beta build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        run: fastlane upload_testflight_beta distribute_external:true

  deploy-production:
    name: Deploy production
    needs: build
    runs-on: [self-hosted, ios-prod]
    timeout-minutes: 120
    steps:
      - name: Upload the Production build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        run: fastlane upload_testflight_production distribute_external:true
